name: easey
version: 0.1.0.0
github: "emekoi/easey"
license: MIT
author: "emekoi"
maintainer: "emekankurumeh@outlook.com"
copyright: "Copyright (c) 2020 Emeka Nkurumeh"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/emekoi/easey#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  easey-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - easey
